name: growerp
version: 0.0.1+1

environment:
  sdk: ">=2.6.2 <3.0.0"

dependencies:
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_form_bloc: ^0.12.0
  flutter_bloc: ^3.2.0
  dio: ^3.0.9
  equatable: ^1.1.0
  meta: ^1.1.6
  devicelocale: ^0.2.2
  rxdart: ^0.23.1
  shared_preferences: ^0.5.6+1
  liquid_progress_indicator: ^0.3.2
  image_picker: ^0.6.2+3
#  flushbar: ^1.9.1
  flushbar:
    git:
      url: git://github.com/valterh4ck3r/flushbar.git
  groovin_widgets: ^1.4.5
  flutter_keychain: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/growerp.png
    - assets/growerp.jpg

