name: growerp
version: 0.0.1+1

environment:
  sdk: ">=2.6.2 <3.0.0"

dependencies:
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: ^1.2.0
  flutter_bloc: ^6.0.0
  dio: ^3.0.9
  meta: ^1.1.6
  shared_preferences: ^0.5.6
  image_picker: ^0.6.2+3
  flutter_staggered_grid_view: ^0.3.0
  about: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  test_coverage: ^0.4.0
  bloc_test: ^7.0.0
  flutter_launcher_icons: ^0.7.5
# to run icons: flutter pub run flutter_launcher_icons:main 
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/growerp.jpg"

flutter:
  uses-material-design: true
# from https://www.flaticon.com/
  assets:
    - assets/
