name: growerp
version: 0.0.1+1

environment:
  sdk: ">=2.6.2 <3.0.0"

dependencies:
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: ^1.1.1
  flutter_bloc: ^3.2.0
  flutter_form_bloc: ^0.13.1
  dio: ^3.0.9
  money: ^0.2.1
  meta: ^1.1.6
  devicelocale: ^0.2.2
  rxdart: ^0.23.1
  shared_preferences: ^0.5.6+1
  liquid_progress_indicator: ^0.3.2
  image_picker: ^0.6.2+3
#  flushbar: ^1.9.1
  flushbar:
    git:
      url: git://github.com/valterh4ck3r/flushbar.git
  groovin_widgets: ^1.4.5
  flutter_keychain: ^1.0.0
  animations: ^1.0.0+5
  date_utils: ^0.1.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  test_coverage: ^0.4.0
  bloc_test: ^4.0.0

flutter:
  uses-material-design: true
# from https://www.flaticon.com/
  assets:
    - assets/growerp.png
    - assets/growerp.jpg
